# Generated by Django 2.1.4 on 2019-09-20 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapproval',
            name='destination_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals_as_destination', to='river.State', verbose_name='Next State'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_approvals', to='river.TransitionApprovalMeta', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='source_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals_as_source', to='river.State', verbose_name='Source State'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='transactioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Transactioner'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_approvals', to='river.Workflow', verbose_name='Workflow'),
        ),
    ]
