# Generated by Django 3.0.6 on 2020-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
