# Generated by Django 2.2.13 on 2020-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_workflow_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Workflow Name'),
        ),
    ]
