# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0005_auto_20191020_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
