# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('river', '0007_transitionapproval_iteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='onapprovedhook',
            name='transition_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_approved_hooks', to='river.TransitionApproval',
                                    verbose_name='Transition Approval'),
        ),
        migrations.AlterField(
            model_name='onapprovedhook',
            name='transition_approval_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_approved_hooks', to='river.TransitionApprovalMeta', verbose_name='Transition Approval Meta'),
        ),
        migrations.AlterUniqueTogether(
            name='onapprovedhook',
            unique_together=set([('callback_function', 'workflow', 'transition_approval_meta', 'content_type', 'object_id', 'transition_approval')]),
        )
    ]
