# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-10 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0008_auto_20191109_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionapproval',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='skipped',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='skipped_from',
        ),
    ]
