# Generated by Django 2.0.7 on 2018-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0009_auto_20170124_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceeding',
            name='object_id',
            field=models.CharField(max_length=50, verbose_name='Related Object'),
        ),
    ]
