# Generated by Django 2.2.8 on 2019-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0012_auto_20191113_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('done', 'Done'), ('jumped', 'Jumped')], default='pending', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transitionapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('jumped', 'Jumped')], default='pending', max_length=100, verbose_name='Status'),
        ),
    ]
